### ISSUE TITLE
Improve docker example

### ISSUE THREAD

**Issue by jcormier** [threatpatrols/docker-sshamble#1]
The given example is appreciated in its simplicity, however it doesn't let you easily run the analyze step.  The analyze step needs to write multiple files so I think it would make sense to update the example so both running the scan and analyze is possible.

Though I wish docker had a less verbose way of doing this...

Scan
```
docker run --rm -it -v $PWD:$PWD -w $PWD -u $(id -u):$(id -g) threatpatrols/sshamble:latest scan -o results.json 10.0.0.0/24
```

Analyze
```
docker run --rm -it -v $PWD:$PWD -w $PWD -u $(id -u):$(id -g)  threatpatrols/sshamble:latest analyze -o results-directory results.json
ls -la 
drwxr-xr-x  2 user    user     4096 Oct  7 10:27 results-directory/
-rw-rw-r--  1   user    user  15388  Oct  7 10:22 results.json
```

We can wrap this in a script, which makes life a little easier:

sshamble.sh:
```
DOCKER_IMAGE=threatpatrols/sshamble:latest
OWNER="-u $(id -u):$(id -g)"
WORKDIR="-v $PWD:$PWD -w $PWD"
# Check for interactive tty
test -t 1 && USE_TTY="-it"
CMD=$@

# Always run latest version
docker pull "$DOCKER_IMAGE"
docker run --rm $USE_TTY $WORKDIR $OWNER $DOCKER_IMAGE $CMD
```

Then assuming the script is in your path, the example docs become

Scan
```
sshamble.sh scan -o results.json 10.0.0.0/24
```

Analyze
```
sshamble.sh analyze -o results-directory results.json
```
Or if we remove the .sh from the script name, then it looks exactly as if we had it installed natively...

**Comment by ndejong** [comment]
Hi @jcormier nice suggestion and added at https://github.com/threatpatrols/docker-sshamble/commit/ad505e5b634ee20ada581bdb94656c6179e6894c

Also improved the bad-keys handling so they are available when the container is used using non-root

**Comment by jcormier** [comment]
Glad to hear.  As an aside, as an IT security poser.  I've run the scan on our network.  Are there specific report files I should be paying close attention to?
